#version 450
#extension GL_EXT_nonuniform_qualifier : require
#extension GL_EXT_buffer_reference : require
#extension GL_EXT_buffer_reference2 : require
#extension GL_EXT_shader_explicit_arithmetic_types_int64 : require
#extension GL_EXT_debug_printf: enable
#extension GL_GOOGLE_include_directive : require

#include "includes.glsl"

struct RoadSegmentNode {
    Bounds bounds;
    uint split_axis;
    float split_value;
    uint is_leaf;
    uint data_0;
    uint data_1;
};

layout(std430, set = 0, binding = 0) readonly buffer RoadSegmentBuffer {
    RoadSegment data[];
} road_segments;

layout(std430, set = 0, binding = 1) readonly buffer RoadSegmentNodeBuffer {
    RoadSegmentNode data[];
} road_node_segments;

layout(std430, set = 0, binding = 2) buffer VertexBuffer {
    Vertex data[];
} vertices;

layout(std430, set = 0, binding = 3) readonly buffer IndexBuffer {
    uint data[];
} indices;

layout(push_constant) uniform PushConstants
{
    uint road_segment_buffer_size;
    uint overlay_option_idx;
} push_constants;


bool polygon_intersection_sat(vec2 road_segments[CORNERS_COUNT], vec2 v[3])
{
    // check every edge of road_segment
    for (int r_i = 0; r_i < CORNERS_COUNT; r_i++)
    {
        vec2 p0 = road_segments[r_i];
        vec2 p1 = road_segments[(r_i + 1) % CORNERS_COUNT];
        vec2 r_v = p0 - p1;
        vec2 n = vec2(-r_v.y, r_v.x);

        // find max interval for road segment points project to normal vector n
        float p2_dot = dot(road_segments[(r_i+2) % CORNERS_COUNT] - p0, n);
        float p3_dot = dot(road_segments[(r_i+3) % CORNERS_COUNT] - p0, n);

        float min_seg = min(0.0, min(p2_dot, p3_dot));
        float max_seg = max(0.0, max(p2_dot, p3_dot));

        // find max interval for triangle points project to normal vector n
        float min_face = min(dot(v[0] - p0, n), min(dot(v[1] - p0, n), dot(v[2] - p0, n)));
        float max_face = max(dot(v[0] - p0, n), max(dot(v[1] - p0, n), dot(v[2] - p0, n)));

        if (min_face > max_seg || max_face < min_seg) {
            return false;
        }
    }

    // check every edge of triangle
    for (int t_i = 0; t_i < 3; t_i++)
    {
        vec2 p0 = v[t_i];
        vec2 p1 = v[(t_i + 1) % 3];
        vec2 t_v = p0 - p1;
        vec2 n = vec2(-t_v.y, t_v.x);

        // find max interval for remaining triangle point project to normal vector n
        float opposite_dot = dot(v[(t_i+2) % 3] - p0, n);
        float min_triangle = min(0.0, opposite_dot);
        float max_triangle = max(0.0, opposite_dot);

        float min_seg = min(min(dot(road_segments[0] - p0, n), dot(road_segments[1] - p0, n)),
                            min(dot(road_segments[2] - p0, n), dot(road_segments[3] - p0, n)));
        float max_seg = max(max(dot(road_segments[0] - p0, n), dot(road_segments[1] - p0, n)),
                            max(dot(road_segments[2] - p0, n), dot(road_segments[3] - p0, n)));

        if (min_triangle > max_seg || max_triangle < min_seg) {
            return false;
        }
    }

    return true;
}

layout(local_size_x = 256, local_size_y = 1, local_size_z = 1) in;
void main()
{
    uint index = gl_GlobalInvocationID.x;
    uint base = index * 3;
    if (base + 2 >= indices.data.length()) {
        return;
    }
    uint v0_idx = indices.data[base];
    uint v1_idx = indices.data[base + 1];
    uint v2_idx = indices.data[base + 2];

    vec3 v0 = vec3(vertices.data[v0_idx].pos_x, vertices.data[v0_idx].pos_y, vertices.data[v0_idx].pos_z);
    vec3 v1 = vec3(vertices.data[v1_idx].pos_x, vertices.data[v1_idx].pos_y, vertices.data[v1_idx].pos_z);
    vec3 v2 = vec3(vertices.data[v2_idx].pos_x, vertices.data[v2_idx].pos_y, vertices.data[v2_idx].pos_z);
    vec3 pos_avg = (v0 + v1 + v2) / 3.0;
    vec2 triangle[3] = {v0.xy, v1.xy, v2.xy};

    uint stack[64];
    int stack_ptr = 0;
    stack[stack_ptr++] = 0u;

    while (stack_ptr > 0)
    {
        RoadSegmentNode cur = road_node_segments.data[stack[--stack_ptr]];

        if (!triangle_bounds_overlap(cur.bounds, triangle))
            continue;

        if (cur.is_leaf != 0u)
        {
            for (uint i = cur.data_0; i < cur.data_1; i++)
            {
                vec2 road_segment[CORNERS_COUNT] = road_segments.data[i].positions;
                bool do_intersec = polygon_intersection_sat(road_segment, triangle);
                if (do_intersec)
                {
                    vertices.data[v0_idx].overlay_option = road_segments.data[i].options[push_constants.overlay_option_idx];
                    vertices.data[v1_idx].overlay_option = road_segments.data[i].options[push_constants.overlay_option_idx];
                    vertices.data[v2_idx].overlay_option = road_segments.data[i].options[push_constants.overlay_option_idx];

                    return;
                }
            }
        }
        else
        {
            if (pos_avg[cur.split_axis] < cur.split_value)
            {
                stack[stack_ptr++] = cur.data_1;
                stack[stack_ptr++] = cur.data_0;
            }
            else
            {
                stack[stack_ptr++] = cur.data_0;
                stack[stack_ptr++] = cur.data_1;
            }
        }
    }
}
