set(VCPKG_TARGET_ARCHITECTURE x64)
set(VCPKG_CRT_LINKAGE dynamic)
set(VCPKG_LIBRARY_LINKAGE static)

# Enable AddressSanitizer
set(VCPKG_CMAKE_CONFIGURE_OPTIONS -DCMAKE_CXX_FLAGS="/EHsc /fsanitize=address /Zi /D_ANNOTATE_STRING=1 /D_ANNOTATE_VECTOR=1" -DCMAKE_EXE_LINKER_FLAGS="/INCREMENTAL:NO")
