name: publish

on:
  push:
    branches:
      - releases
    tags:
      - "*"
jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-24.04, windows-2022]
        include:
          - os: ubuntu-24.04
            zip_type: linux-x64.tar.gz
          - os: windows-2022
            zip_type: windows-x64.zip
    env:
      ZIP_NAME: DTCity-${{ github.ref_name }}-${{ matrix.zip_type }}
    runs-on: ${{ matrix.os}}
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Windows
        if: matrix.os == 'windows-2022'
        shell: cmd
        run: |
          call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvarsall.bat" x64
          set "VCPKG_ROOT=%GITHUB_WORKSPACE%\vcpkg"
          git clone https://github.com/microsoft/vcpkg.git %VCPKG_ROOT%
          call %VCPKG_ROOT%\bootstrap-vcpkg.bat
          cmake --preset=release-windows
          cmake --build build
          %SystemRoot%\System32\tar.exe -a -c -f ${{ env.ZIP_NAME }} build/city.exe data/*
      - name: Build Linux
        if: matrix.os == 'ubuntu-24.04'
        shell: bash
        run: |
          sudo apt-get update
          sudo apt-get install -y libgl1-mesa-dev xorg-dev libwayland-dev libxkbcommon-dev wayland-protocols extra-cmake-modules
          git clone https://github.com/microsoft/vcpkg.git ~/vcpkg
          cd ~/vcpkg
          ./bootstrap-vcpkg.sh
          VCPKG_ROOT=~/vcpkg
          cmake --preset=release-linux
          cmake --build build
          tar -czf ${{ env.ZIP_NAME }} build/city data/*

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        if: github.ref_type == 'tag'
        with:
          tag_name: ${{ github.ref_name }}
          files: ${{ env.ZIP_NAME }}
          draft: false
          prerelease: true
          generate_release_notes: true
